"""add account Balance to user

Revision ID: 1971a105dd0d
Revises: 615ffb8be7f5
Create Date: 2025-11-25 21:51:05.214580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1971a105dd0d'
down_revision: Union[str, Sequence[str], None] = '615ffb8be7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_users', sa.Column('account_balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_users', 'account_balance')
    # ### end Alembic commands ###
