"""add account Balance to user

Revision ID: a1bbca78705c
Revises: 270036b20550
Create Date: 2025-11-25 22:07:56.154501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bbca78705c'
down_revision: Union[str, Sequence[str], None] = '270036b20550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_ibfk_2'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_ibfk_1'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'registered_users', ['to_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'registered_users', ['from_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_ibfk_1'), 'transactions', 'bank', ['from_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('transactions_ibfk_2'), 'transactions', 'bank', ['to_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
